# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: AzureApp"
kfutil store-types create AzureApp

Write-Host "Creating store type: AzureSP"
kfutil store-types create AzureSP

Write-Host "Creating store type: AzureApp2"
kfutil store-types create AzureApp2

Write-Host "Creating store type: AzureSP2"
kfutil store-types create AzureSP2

