# Creates all 4 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# AzureApp — The Azure Tenant (directory) ID that owns the Service Principal.
# ---------------------------------------------------------------------------
New-StoreType "AzureApp" @'
{
  "Name": "Azure App Registration (Application)",
  "ShortName": "AzureApp",
  "Capability": "AzureApp",
  "LocalStore": false,
  "StorePathDescription": "The Application ID of the target Application/Service Principal that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

# ---------------------------------------------------------------------------
# AzureSP — The Azure Tenant (directory) ID that owns the Service Principal.
# ---------------------------------------------------------------------------
New-StoreType "AzureSP" @'
{
  "Name": "Azure Enterprise Application (Service Principal)",
  "ShortName": "AzureSP",
  "Capability": "AzureSP",
  "LocalStore": false,
  "StorePathDescription": "The Application ID of the target Application/Service Principal that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

# ---------------------------------------------------------------------------
# AzureApp2 — The Azure Tenant (directory) ID where the Application is instantiated
# ---------------------------------------------------------------------------
New-StoreType "AzureApp2" @'
{
  "Name": "Azure App Registration 2 (Application)",
  "ShortName": "AzureApp2",
  "Capability": "AzureApp2",
  "LocalStore": false,
  "StorePathDescription": "The Object ID of the target Application/App Registration that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

# ---------------------------------------------------------------------------
# AzureSP2 — The Azure Tenant (directory) ID where the Service Principal is instantiated
# ---------------------------------------------------------------------------
New-StoreType "AzureSP2" @'
{
  "Name": "Azure Enterprise Application 2 (Service Principal)",
  "ShortName": "AzureSP2",
  "Capability": "AzureSP2",
  "LocalStore": false,
  "StorePathDescription": "The Object ID of the target Service Principal/Enterprise Application that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@


Write-Host "Completed."
