# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: AzureApp"
$Body = @'
{
  "Name": "Azure App Registration (Application)",
  "ShortName": "AzureApp",
  "Capability": "AzureApp",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "The Application ID of the Service Principal used to authenticate with Microsoft Graph for managing Application/Service Principal certificates.",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with Microsoft Graph for managing Application/Service Principal certificates, OR the password that encrypts the private key in ClientCertificate. If Client Cert Auth is used _and_ the Client Certificate's private key is not encrypted, you **must** select 'No Value' for this field.",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Microsoft Graph for managing Application/Service Principal certificates. See the [requirements](#client-certificate-or-client-secret) for more information. If Client Certificate Auth is not used, you **must** select 'No Value' for this field.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: AzureSP"
$Body = @'
{
  "Name": "Azure Enterprise Application (Service Principal)",
  "ShortName": "AzureSP",
  "Capability": "AzureSP",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "The Application ID of the Service Principal used to authenticate with Microsoft Graph for managing Application/Service Principal certificates.",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with Microsoft Graph for managing Application/Service Principal certificates, OR the password that encrypts the private key in ClientCertificate. If Client Cert Auth is used _and_ the Client Certificate's private key is not encrypted, you **must** select 'No Value' for this field.",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Microsoft Graph for managing Application/Service Principal certificates. See the [requirements](#client-certificate-or-client-secret) for more information. If Client Certificate Auth is not used, you **must** select 'No Value' for this field.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: AzureApp2"
$Body = @'
{
  "Name": "Azure App Registration 2 (Application)",
  "ShortName": "AzureApp2",
  "Capability": "AzureApp2",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "The Application ID of the Service Principal used to authenticate with Microsoft Graph for managing Application/App Registration certificates.",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with Microsoft Graph for managing Application/App Registration certificates. If Client Certificate Auth is used, you **must** select 'No Value'.",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Microsoft Graph for managing Application/App Registrations certificates. See the [requirements](#client-certificate-or-client-secret) for more information. If Client Certificate Auth is not used, you **must** check 'No Value'.",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Description": "The (optional) password that encrypts the private key in ClientCertificate.  If Client Certificate Auth is not used, you **must** check 'No Value'.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: AzureSP2"
$Body = @'
{
  "Name": "Azure Enterprise Application 2 (Service Principal)",
  "ShortName": "AzureSP2",
  "Capability": "AzureSP2",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "The Application ID of the Service Principal used to authenticate with Microsoft Graph for managing Service Principal/Enterprise Application certificates.",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Description": "A Client Secret that the extension will use to authenticate with Microsoft Graph for managing Service Principal/Enterprise Application certificates. If Client Certificate Auth is used, you **must** check 'No Value'.",
      "Required": false
    },
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Description": "The client certificate used to authenticate with Microsoft Graph for managing Service Principal/Enterprise Application certificates. See the [requirements](#client-certificate-or-client-secret) for more information. If Client Certificate Auth is not used, you **must** check 'No Value'.",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Description": "The (optional) password that encrypts the private key in ClientCertificate. If Client Certificate Auth is not used or the certificate's private key is not encrypted, you **must** check 'No Value'.",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Description": "Specifies the Azure Cloud instance used by the organization.",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

