#!/usr/bin/env bash

# Creates all 4 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# AzureApp — The Azure Tenant (directory) ID that owns the Service Principal.
# ---------------------------------------------------------------------------
create_store_type "AzureApp" '{
  "Name": "Azure App Registration (Application)",
  "ShortName": "AzureApp",
  "Capability": "AzureApp",
  "LocalStore": false,
  "StorePathDescription": "The Application ID of the target Application/Service Principal that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

# ---------------------------------------------------------------------------
# AzureSP — The Azure Tenant (directory) ID that owns the Service Principal.
# ---------------------------------------------------------------------------
create_store_type "AzureSP" '{
  "Name": "Azure Enterprise Application (Service Principal)",
  "ShortName": "AzureSP",
  "Capability": "AzureSP",
  "LocalStore": false,
  "StorePathDescription": "The Application ID of the target Application/Service Principal that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

# ---------------------------------------------------------------------------
# AzureApp2 — The Azure Tenant (directory) ID where the Application is instantiated
# ---------------------------------------------------------------------------
create_store_type "AzureApp2" '{
  "Name": "Azure App Registration 2 (Application)",
  "ShortName": "AzureApp2",
  "Capability": "AzureApp2",
  "LocalStore": false,
  "StorePathDescription": "The Object ID of the target Application/App Registration that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Forbidden",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

# ---------------------------------------------------------------------------
# AzureSP2 — The Azure Tenant (directory) ID where the Service Principal is instantiated
# ---------------------------------------------------------------------------
create_store_type "AzureSP2" '{
  "Name": "Azure Enterprise Application 2 (Service Principal)",
  "ShortName": "AzureSP2",
  "Capability": "AzureSP2",
  "LocalStore": false,
  "StorePathDescription": "The Object ID of the target Service Principal/Enterprise Application that will be managed by the Azure App Registration and Enterprise Application Orchestrator extension.",
  "SupportedOperations": {
    "Add": true,
    "Remove": true,
    "Enrollment": false,
    "Discovery": true,
    "Inventory": true
  },
  "Properties": [
    {
      "Name": "ClientCertificate",
      "DisplayName": "Client Certificate",
      "DependsOn": "ServerUsername",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "ClientCertificatePassword",
      "DisplayName": "Client Certificate Password",
      "DependsOn": "ClientCertificate",
      "Type": "Secret",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Global Cloud Authority Host",
      "Type": "MultipleChoice",
      "DefaultValue": "public,china,germany,government",
      "Required": false
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'


echo "Completed."
