#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: AzureApp"
kfutil store-types create AzureApp

echo "Creating store type: AzureSP"
kfutil store-types create AzureSP

echo "Creating store type: AzureApp2"
kfutil store-types create AzureApp2

echo "Creating store type: AzureSP2"
kfutil store-types create AzureSP2

